apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-11-11T15:30:56Z"
  generation: 1
  labels:
    app: tf-k8s-jenkins
  name: tf-k8s-jenkins
  namespace: default
  resourceVersion: "603252"
  uid: e3a9cecc-a979-4046-8193-7053c7de8ece
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tf-k8s-jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tf-k8s-jenkins
    spec:
      containers:
      - image: devopsgoofy/tf-k8s-jenkins:latest
        imagePullPolicy: Always
        name: tf-k8s-jenkins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
