---
- hosts: k8s_cluster
  become: yes
  tasks:
    - name: Update package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - curl
          - apt-transport-https
          - ca-certificates
          - gpg
        state: present

    - name: Add CRI-O GPG key
      command: curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
      args:
        warn: false
      when: ansible_distribution == 'Ubuntu'

    - name: Add CRI-O APT repository
      copy:
        content: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/ /\n"
        dest: /etc/apt/sources.list.d/cri-o.list

    - name: Install CRI-O
      apt:
        name: cri-o
        state: present

    - name: Start and enable CRI-O
      systemd:
        name: crio
        state: started
        enabled: yes

    - name: Disable swap
      command: swapoff -a

    - name: Load kernel modules for Kubernetes
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        create: yes
      loop:
        - overlay
        - br_netfilter

    - name: Load kernel modules now
      command: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter

    - name: Set sysctl parameters for Kubernetes
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply sysctl parameters without reboot
      command: sysctl --system

    - name: Add Kubernetes GPG key
      command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        warn: false

    - name: Add Kubernetes APT repository
      copy:
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /\n"
        dest: /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold kubelet, kubeadm, and kubectl versions
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Enable kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: yes
